# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [created]

env:
  MAILOSAUR_BASE_URL: https://mailosaur.com/
  MAILOSAUR_SMTP_HOST: mailosaur.io
  MAILOSAUR_SMTP_PORT: 2525
  MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
  MAILOSAUR_SERVER: ${{ secrets.MAILOSAUR_SERVER }}

jobs:
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: version
        run: |
          npm version `git describe --abbrev=0 --tags`
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
